web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    build: .
    volumes:
        - ./code:/code
    links:
        - mysql
mysql:
    image: mysql:latest
    ports: 
        - "3307:3306"
    environment:
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel 
        MYSQL_PASSWORD: password 
        MYSQL_ROOT_PASSWORD: password
    volumes:
        - ./mysqldata:/var/lib/mysql/
